### ISSUE TITLE
Awful weather tonight?

### ISSUE THREAD

**Issue by minin43** [akstoulil/Group-Project-1#9]
Gonna delete this later.

Anyone else considering not attending class tonight? Given how awful the roads were on Tuesday, and how we're supposed to get something similar tonight (rain into ice), I'm worried about driving.

But, I also feel bad for missing so many classes. We're a group, right? We need to work together. Not going to class means falling even more behind, but is it worth the risk?

**Comment by akstoulil** [comment]
Yeah, I know what you mean. I don't think I am probably going to make it to class tonight, since it sounds like there is going to be freezing rain and snow. I'll try to keep in touch about the group project and such.

**Comment by minin43** [comment]
Yea I just checked the radar, we're supposed to get hit by steady rain at 8:30. Right as we hit freezing temps (we've been sitting at 32 degrees so far all day) hit. Gonna email the professor and let him know.

**Comment by CrazyCarl78** [comment]
I'm not going to class tonight. The temperature is getting colder. I don't want to chance it.

**Comment by agkingrey** [comment]
Yeah, everything around the area is closing up, I'm out as well.
